const $=id=>document.getElementById(id),signToken=location.pathname.startsWith('/sign/')?location.pathname.split('/').pop():'';
const api=async(path,body,method='POST')=>{const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}),x=await r.json().catch(()=>({}));if(!r.ok)throw Error(x.error||'Ошибка');return x};
const sberLogin=()=>location.assign('/v1/auth/sber/start?return_to='+encodeURIComponent(location.pathname));
function showLogin(){const a=$('auth');a.hidden=false;a.innerHTML='<span class="eyebrow">Безопасный вход</span><h1>Войдите через Сбер ID</h1><p>Демо-вход отключён. Номер телефона, подтверждённый Сбер ID, используется для идентификации участника сделки.</p><button id="sberLogin">Продолжить со Сбер ID</button>'; $('sberLogin').onclick=sberLogin}
function signedInContractor(){const b=$('auth');b.innerHTML='<span class="eyebrow">Безопасное подписание</span><h1>Подпишите документ</h1><p>Личность подтверждена через Сбер ID. Для ПЭП потребуется одноразовый код от подключённого SMS-провайдера.</p><label class="agreement"><input id="pepAgreement" type="checkbox"> Я принимаю Соглашение ЭДО и подтверждаю ПЭП</label><button id="pepRequest">Получить код подписи</button><div id="pepConfirm" hidden><label>Код подписи<input id="pepCode" inputmode="numeric" maxlength="6"></label><button id="pepSign">Подписать документ</button></div>'; $('pepRequest').onclick=requestPep;$('pepSign').onclick=confirmPep}
async function requestPep(){try{if(!$('pepAgreement').checked)throw Error('Подтвердите согласие с Соглашением ЭДО');await api('/v1/signing/'+signToken+'/pep/request');$('pepConfirm').hidden=false}catch(e){alert(e.message)}}
async function confirmPep(){try{const d=await api('/v1/signing/'+signToken+'/pep/confirm',{code:$('pepCode').value,agreementAccepted:$('pepAgreement').checked});$('auth').innerHTML='<div class="result"><strong>Документ подписан ПЭП</strong><br>Статус: '+d.Status+'</div>'}catch(e){alert(e.message)}}
async function boot(){let me;try{me=await api('/v1/auth/me',null,'GET')}catch(_){showLogin();return}if(signToken){$('workspace').hidden=true;signedInContractor();return}$('auth').hidden=true;$('workspace').hidden=false;$('logout').onclick=async()=>{await api('/v1/auth/logout');location.assign('/')};$('create').onsubmit=async e=>{e.preventDefault();try{const d=await api('/v1/documents',{title:$('title').value,template:$('template').value,contractorPhone:$('contractor').value,content:$('content').value,edoAgreementVersion:'2026-08-01',amountKopecks:Math.round(+$('amount').value*100)});const file=$('file').files[0];if(file){const r=await fetch('/v1/documents/'+d.ID+'/file',{method:'PUT',body:file});if(!r.ok)throw Error((await r.json()).error||'Не удалось загрузить файл')}const sent=await api('/v1/documents/'+d.ID+'/send');$('result').innerHTML='<strong>Документ создан</strong><br>Статус: '+d.Status+'<br><br>Ссылка для исполнителя:<br><a href="'+sent.signingUrl+'" target="_blank">'+sent.signingUrl+'</a>'}catch(err){alert(err.message)}}}
boot();
